<div class="container-principal" id="cadastrado_sucesso">

	<div class="topo color-default">
		<div class="row">
			<div class="col-12 col-md-12 d-flex justify-content-center">
				<h1 class="Logo"><i class="fab fa-drupal"></i><span>Mailbox</span></h1>
			</div>
		</div>
	</div>

	<div class="container mt-5">
		<div class="row mb-2">
			<div class="col-12 text-center">
				<h1 class="display-2 font-weight-bold">Cadastrado com sucesso!</h1>
			</div>
		</div>
	

	
		<div class="row mt-5">
			<div class="col-12 text-center">
				<h1 class="display-2 font-weight-bold">Seja bem vindo</h1>
			</div>
		</div>
	

		<div class="d-flex justify-content-end">
			<a href="/" class="btn btn-lg color-default text-white">Voltar</a>
		</div>
	</div>


</div>