<?php
	
	/*echo "<pre>";
	$usuario = $this->view->usuario;
	print_r($usuario);
	$mensagem = $this->view->erroCadastro;
	print_r($mensagem);
	echo "</pre>";

	//$info = isset($this->view->usuario);*/

?>


<div class="container-principal" id="cadastrar">

	<div class="topo color-default">
		<div class="row">
			<div class="col-12 col-md-12 d-flex justify-content-center">
				<h1 class="Logo"><i class="fab fa-drupal"></i><span>Mailbox</span></h1>
			</div>
		</div>
	</div>

	<div class="meio">
		<div class="container">
			<div class="row">
				<div class="col-12">

						<div class="modal-personalizado color-default">
							<form id="form_dados" action="/cadastrar" method="post">
								
								<!--<div class="header-modal">
									<i class="fab fa-drupal logo-header-modal"></i>
								</div>-->

								<div class="body-modal">

									<div class="form-row">
									    <div class="form-group col-md-6">
									      <label for="id_nome" class="mt-1 label-componente">Nome</label>
									      <input type="text" class="form-control" id="id_nome" placeholder="Nome" name="nome" value="<?= $this->view->usuario['nome'] ?>">
									    </div>
									    <div class="form-group col-md-6">
									      <label for="id_email" class="mt-1 label-componente">Email</label>
									      <input type="email" class="form-control caixa-baixa" id="id_email_inscreverse" placeholder="Email" name="email" value="<?= $this->view->usuario['email'] ?>">
									    </div>
									</div>

									<div class="d-flex mb-2">
										<label class="text-white label-componente">Sexo: </label>
										<div class="custom-control custom-radio custom-control-inline ml-2">
										  <input type="radio" id="id_sexo_masculino" name="sexo" class="custom-control-input" value="Masculino">
										  <label class="custom-control-label text-white label-sexo" for="id_sexo_masculino">Masculino</label>
										</div>
										<div class="custom-control custom-radio custom-control-inline">
										  <input type="radio" id="id_sexo_feminino" name="sexo" class="custom-control-input" value="feminino">
										  <label class="custom-control-label text-white label-sexo" for="id_sexo_feminino">Feminino</label>
										</div>
									</div>


									<div class="form-row">
									    <div class="form-group col-md-6">
									      <label for="id_senha" class="label-componente">Senha</label>
									      <input type="password" class="form-control" id="id_senha" placeholder="Senha" name="senha">
									    </div>
									    <div class="form-group col-md-6">
									      <label for="id_senha_confirmar" class="label-componente">Confirmar Senha</label>
									      <input type="password" class="form-control" id="id_senha_confirmar" placeholder="Confirmar Senha" name="senha_confirm">
									    </div>
									</div>

									<div class="form-row">
										<div class="form-group" style="width: 50%">
									    	<label for="id_data_nascimento" class="label-componente">Data Nascimento</label>
									    	<input type="date" class="form-control" id="id_data_nascimento" name="data_nascimento" value="<?= $this->view->usuario['data_nascimento'] ?>">
										</div>
									</div>
									

									<div class="form-group" style="width: 65%">
									    <label for="id_telefone" class="label-componente">Telefone</label>
									    <input type="text" class="form-control"  id="id_telefone" name="telefone" placeholder="(00) 0 0000-0000" value="<?= $this->view->usuario['telefone'] ?>">
									</div>
									   
								</div>

								<div class="footer-modal">
									<div class="d-flex justify-content-end">
										<button type="submit" class="btn botao">Cadastrar</button>
										<button type="Reset" class="btn botao">Cancelar</button>
										<a href="/" class="mr-5 botao btn">Voltar</a>
									</div>
								</div>

							</form>	

						</div>
						<div class="mensagem" style="">
						<?php if($this->view->erroCadastro){?>

					        <small class="form-text text-danger">*Erro ao tentar realizar o cadastro, verifique se os campos foram preenchidos corretamente.</small>

					    <?php } ?>
						</div>
						
				</div>
			</div>
		</div>
	</div>

</div>