<?php
	//echo "teste";
	$mensagem = isset($this->view->mensagemEnviado) ? $this->view->mensagemEnviado : '';
	//print_r($_GET);
?>

<div class="container-principal" id="mailbox-enviar">

	<header class="topo color-default">
      <nav class="navbar navbar-expand-md container-menu">
        <div class="container">
            <div>
				<div class="row">
					<div class="col-12 d-flex">
						<h1 class="logo"><i class="fab fa-drupal"></i><span>Mailbox</span></h1>
					</div>
				</div>
			</div>

            <button class="navbar-toggler">
              <i class="fas fa-bars text-white" data-target="#menu-resposivo" data-toggle="collapse"></i>
            </button>
            <div class="navbar-collapse collapse" id="menu-resposivo">
              <ul class="navbar-nav ml-auto menu">
              	
                <li class="d-flex  mr-3 lista-menu"><i class="fas fa-home icon-menu"></i><a class="nav-link link-menu" href="#">Home</a></li>
                <li class="d-flex  mr-3 lista-menu"><i class="fas fa-envelope icon-menu"></i><a class="nav-link link-menu" href="/mailbox">Mailbox</a></li>
                <li class="d-flex  mr-5 lista-menu"><i class="fas fa-search icon-menu"></i><a class="nav-link link-menu" href="/search">Search</a></li>
                <li class="d-flex  mr-2 lista-menu"><i class="fas fa-user icon-menu"></i><a class="nav-link link-menu" href="/profile">Profile</a></li>
      			<li class="d-flex  mr-2 lista-menu"><i class="fas fa-sign-out-alt icon-menu"></i><a class="nav-link link-menu" href="/sair">Logout</a></li>
              </ul>
            </div>
          
        </div>
      </nav>
    </header>

    <div class="meio-message-view">
    	<div class="container-messagem-mailbox-message">
    		<div class="col-8 mt-5 mb-5" style="margin-left: 18%;">
	    		<form action="/enviar_mensagem" method="post">
				  <div class="form-group">
				    <label for="id_destinatario">Destinatário</label>
				    <?php if (isset($_GET['email']) && $_GET['email'] != '') { ?>
				    	<input type="text" class="form-control" id="id_destinatario" name="destinatario" placeholder="Enter destinatário" value="<?= $_GET['email'] ?>">
				    <?php } else { ?>
				    	<input type="text" class="form-control" id="id_destinatario" name="destinatario" placeholder="Enter destinatário">
				    <?php } ?>	
				  </div>

				  <div class="form-group">
				    <label for="id_titulo">Título</label>
				    <input type="text" class="form-control" id="id_titulo" name="titulo" placeholder="Título">
				  </div>

				  <div class="form-group">
				    <label for="id_mensagem">Descrição</label>
				    <textarea class="form-control" id="id_mensagem" name="descricao" rows="3"></textarea>
				  </div>

				  <div class="mt-3 d-flex justify-content-end  mt-5">
					<button type="submit" id="btn_enviar_mensagem" class="btn btn-dark text-white">Enviar Mensagem</button>
				  </div>
				</form>
			</div>
    	</div>

    	<?php if ($mensagem) { ?>
	    	<div class="bg-dark text-white text-center mt-4">
	    		Mensagem Enviada com sucesso!
	    	</div>
	    <?php } ?>
	    		

    </div>
    


	

</div>