<html>
	<head>
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Miniframework</title>
		
		<meta charset="utf-8">
		
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

		<script src="js/jquery-3.3.1.min.js"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">

		<script type="text/javascript" src="js/app.js"></script>
		
		<!-- Sweetalert 2 -->
		<script src="https://cdn.jsdelivr.net/npm/sweetalert2@8"></script>

		<script type="text/javascript" src="js/jquery.validate.min.js"></script>
		<script type="text/javascript" src="js/localization/messages_pt_BR.js"></script>
		<link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
		<script type="text/javascript" src="js/jquery.mask.min.js"></script>

	</head>
	<body>
		<?= $this->content() ?>
	</body>
</html>